# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Extract < Formula
  desc "file extractor"
  homepage "https://github.com/terencendabereye/util-extract"
  version "0.1.2-rc1"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/terencendabereye/util-extract/releases/download/v0.1.2-rc1/util-extract_Darwin_arm64.tar.gz"
      sha256 "5572e2e0810ffefbc0ba0374cb2bd3fcc35fcfd6c9ce6569a88f7cbbf07283dd"

      def install
        bin.install "util-extract"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/terencendabereye/util-extract/releases/download/v0.1.2-rc1/util-extract_Darwin_x86_64.tar.gz"
      sha256 "4cd290733d7dfa631438440269ee4a2306a70ebba28fb30b9903b7beb86923b1"

      def install
        bin.install "util-extract"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/terencendabereye/util-extract/releases/download/v0.1.2-rc1/util-extract_Linux_arm64.tar.gz"
      sha256 "2436d2ef1f48154596778a29e974535f37239f7702cebc51f1798bb2b8be86c4"

      def install
        bin.install "util-extract"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/terencendabereye/util-extract/releases/download/v0.1.2-rc1/util-extract_Linux_x86_64.tar.gz"
      sha256 "81d232da262266086f2f8914d4bff91e8b326e46c41b2e3364b27086397db506"

      def install
        bin.install "util-extract"
      end
    end
  end
end
