# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Extract < Formula
  desc "file extractor"
  homepage "https://github.com/terencendabereye/util-extract"
  version "0.1.2"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/terencendabereye/util-extract/releases/download/v0.1.2/util-extract_Darwin_arm64.tar.gz"
      sha256 "2326a73d4ae77431385c1efe52c195eaf5a44808d60bd948b44bca4f4e78d533"

      def install
        bin.install "util-extract"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/terencendabereye/util-extract/releases/download/v0.1.2/util-extract_Darwin_x86_64.tar.gz"
      sha256 "5c30512fde661dc484fe497b17b82a04a54406742c1e1da0c62931e17636e1e2"

      def install
        bin.install "util-extract"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/terencendabereye/util-extract/releases/download/v0.1.2/util-extract_Linux_arm64.tar.gz"
      sha256 "29130e698b5ddc5093984813d4f96882fbde193419bfdd14dc67649a8e4c2623"

      def install
        bin.install "util-extract"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/terencendabereye/util-extract/releases/download/v0.1.2/util-extract_Linux_x86_64.tar.gz"
      sha256 "0a757bdbf721f23b0d99fe8c753ceed05127899446e2cd85990b6e0b58fdaa1f"

      def install
        bin.install "util-extract"
      end
    end
  end
end
